on:
  push

jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Setup DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx

    - name: DocFX Build
      run: docfx .\docfx.json
      continue-on-error: false

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        force_orphan: true